"""removed columns from the user table 

Revision ID: 0e5c3338b244
Revises: 581fba722114
Create Date: 2023-10-03 18:14:30.260170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e5c3338b244'
down_revision = '581fba722114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_type')
        batch_op.drop_column('admin')
        batch_op.drop_column('last_login')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('admin', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('user_type', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
