"""dropped the phone_number column

Revision ID: 1c5c7f64c5d8
Revises: 8856bc2c0bfe
Create Date: 2023-10-03 10:12:46.726121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c5c7f64c5d8'
down_revision = '8856bc2c0bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint('Customer_unique_constraint', type_='unique')
        batch_op.create_unique_constraint('Customer_unique_constraint', ['email'])
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_constraint('Vendor_unique_constraint', type_='unique')
        batch_op.create_unique_constraint('Vendor_unique_constraint', ['email'])
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('Vendor_unique_constraint', type_='unique')
        batch_op.create_unique_constraint('Vendor_unique_constraint', ['phone_number', 'email'])

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('Customer_unique_constraint', type_='unique')
        batch_op.create_unique_constraint('Customer_unique_constraint', ['phone_number', 'email'])

    # ### end Alembic commands ###
