"""add user_id to vendor and customer

Revision ID: 38e0a8c0a430
Revises: 9b6c650a7e19
Create Date: 2023-10-03 23:37:45.892901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38e0a8c0a430'
down_revision = '9b6c650a7e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
