"""added admin column in users table

Revision ID: 711a28c44606
Revises: 1944b58498fd
Create Date: 2023-10-03 14:37:13.047218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711a28c44606'
down_revision = '1944b58498fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
