"""destructured the full_name into first and last name and renamed the users table name into username 

Revision ID: 9b6c650a7e19
Revises: c2a40bf9a475
Create Date: 2023-10-03 23:21:07.801696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b6c650a7e19'
down_revision = 'c2a40bf9a475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(), nullable=True))
        batch_op.drop_constraint('User_unique_constraint', type_='unique')
        batch_op.create_unique_constraint('User_unique_constraint', ['public_id', 'user_name'])

    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('User_unique_constraint', type_='unique')
        batch_op.create_unique_constraint('User_unique_constraint', ['public_id'])
        batch_op.drop_column('user_name')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
