"""added customer_id and product_id to the order table 

Revision ID: ecac7feaefde
Revises: 7d20bc49cdc2
Create Date: 2023-10-04 16:51:27.356833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecac7feaefde'
down_revision = '7d20bc49cdc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_orders_customer_id_customer'), 'customer', ['customer_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_orders_product_id_product'), 'product', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_orders_product_id_product'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_orders_customer_id_customer'), type_='foreignkey')
        batch_op.drop_column('product_id')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
