"""added the relationship between categr=ory and products

Revision ID: f0770bf19532
Revises: ff22d2ba7c1c
Create Date: 2023-10-04 18:23:32.998403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0770bf19532'
down_revision = 'ff22d2ba7c1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_product_category_id_categories'), 'categories', ['category_id'], ['id'])
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_product_category_id_categories'), type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
